<a href="https://colab.research.google.com/github/Tharuni-web/AI-AC/blob/main/AIAC17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#TASK-1
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Create a synthetic employee dataset for demonstration
data = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 11],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy', 'Bob', 'Kelly'],
    'designation': ['Software Engineer', 'Project Manager', 'Data Scientist', 'Software Engineer', 'HR Manager', 'Project Manager', 'Software Engineer', 'Data Scientist', 'HR Manager', 'Software Engineer', 'Project Manager', 'Junior Software Engineer'],
    'employment_type': ['Full-time', 'Contract', 'Full-time', 'Full-time', 'Part-time', 'Full-time', 'Full-time', 'Contract', 'Full-time', 'Full-time', 'Contract', 'Full-time'],
    'salary': [70000, 90000, 85000, 72000, 60000, 92000, 71000, 86000, 62000, 73000, np.nan, 65000],
    'experience': [3, 7, 5, 4, 2, 8, 3, 6, 2, 4, 7, np.nan],
    'department': ['Engineering', 'Management', 'Data Science', 'Engineering', 'HR', 'Management', 'Engineering', 'Data Science', 'HR', 'Engineering', 'Management', 'Engineering']
}
df = pd.DataFrame(data)

# Introduce some missing values intentionally for demonstration
df.loc[0, 'salary'] = np.nan
df.loc[4, 'designation'] = np.nan

print("Original DataFrame:")
display(df)
print("\nDataFrame Info:")
df.info()

Original DataFrame:

,employee_id,name,designation,employment_type,salary,experience,department
0,1,Alice,Software Engineer,Full-time,NaN,3.0,Engineering
1,2,Bob,Project Manager,Contract,90000.0,7.0,Management
2,3,Charlie,Data Scientist,Full-time,85000.0,5.0,Data Science
3,4,David,Software Engineer,Full-time,72000.0,4.0,Engineering
4,5,Eve,NaN,Part-time,60000.0,2.0,HR
5,6,Frank,Project Manager,Full-time,92000.0,8.0,Management
6,7,Grace,Software Engineer,Full-time,71000.0,3.0,Engineering
7,8,Heidi,Data Scientist,Contract,86000.0,6.0,Data Science
8,9,Ivan,HR Manager,Full-time,62000.0,2.0,HR
9,10,Judy,Software Engineer,Full-time,73000.0,4.0,Engineering
10,2,Bob,Project Manager,Contract,NaN,7.0,Management
11,11,Kelly,Junior Software Engineer,Full-time,65000.0,NaN,Engineering

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      12 non-null     int64
 1   name             12 non-null     object
 2   designation      11 non-null     object
 3   employment_type  12 non-null     object
 4   salary           10 non-null     float64
 5   experience       11 non-null     float64
 6   department       12 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 804.0+ bytes

## Data Cleaning Steps

### 1. Handle Missing Values

I will fill missing 'salary' values with the median, 'experience' with the mean, and 'designation' with 'Unknown'. These strategies are chosen to minimize impact on the distribution (median/mean for numerical) and to explicitly mark unknown categories.

In [ ]:
# Fill missing 'salary' with the median
df['salary'].fillna(df['salary'].median(), inplace=True)

# Fill missing 'experience' with the mean
df['experience'].fillna(df['experience'].mean(), inplace=True)

# Fill missing 'designation' with 'Unknown'
df['designation'].fillna('Unknown', inplace=True)

print("DataFrame after handling missing values:")
display(df)

DataFrame after handling missing values:

/tmp/ipykernel_5623/19081952.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary'].fillna(df['salary'].median(), inplace=True)
/tmp/ipykernel_5623/19081952.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['experience'].fillna(df['experience'].mean(), inplace=True)
/tmp/ipykernel_5623/19081952.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['designation'].fillna('Unknown', inplace=True)

,employee_id,name,designation,employment_type,salary,experience,department
0,1,Alice,Software Engineer,Full-time,72500.0,3.000000,Engineering
1,2,Bob,Project Manager,Contract,90000.0,7.000000,Management
2,3,Charlie,Data Scientist,Full-time,85000.0,5.000000,Data Science
3,4,David,Software Engineer,Full-time,72000.0,4.000000,Engineering
4,5,Eve,Unknown,Part-time,60000.0,2.000000,HR
5,6,Frank,Project Manager,Full-time,92000.0,8.000000,Management
6,7,Grace,Software Engineer,Full-time,71000.0,3.000000,Engineering
7,8,Heidi,Data Scientist,Contract,86000.0,6.000000,Data Science
8,9,Ivan,HR Manager,Full-time,62000.0,2.000000,HR
9,10,Judy,Software Engineer,Full-time,73000.0,4.000000,Engineering
10,2,Bob,Project Manager,Contract,72500.0,7.000000,Management
11,11,Kelly,Junior Software Engineer,Full-time,65000.0,4.636364,Engineering

### 2. Remove Duplicate Employee IDs

I will remove rows where 'employee_id' is duplicated, keeping only the first occurrence.

In [ ]:
df.drop_duplicates(subset=['employee_id'], keep='first', inplace=True)

print("DataFrame after removing duplicate employee IDs:")
display(df)

DataFrame after removing duplicate employee IDs:

,employee_id,name,designation,employment_type,salary,experience,department
0,1,Alice,Software Engineer,Full-time,72500.0,3.000000,Engineering
1,2,Bob,Project Manager,Contract,90000.0,7.000000,Management
2,3,Charlie,Data Scientist,Full-time,85000.0,5.000000,Data Science
3,4,David,Software Engineer,Full-time,72000.0,4.000000,Engineering
4,5,Eve,Unknown,Part-time,60000.0,2.000000,HR
5,6,Frank,Project Manager,Full-time,92000.0,8.000000,Management
6,7,Grace,Software Engineer,Full-time,71000.0,3.000000,Engineering
7,8,Heidi,Data Scientist,Contract,86000.0,6.000000,Data Science
8,9,Ivan,HR Manager,Full-time,62000.0,2.000000,HR
9,10,Judy,Software Engineer,Full-time,73000.0,4.000000,Engineering
11,11,Kelly,Junior Software Engineer,Full-time,65000.0,4.636364,Engineering

### 3. Standardize Text Values (Job Titles in Lowercase)

I will convert the 'designation' column to lowercase to standardize job titles.

In [ ]:
df['designation'] = df['designation'].str.lower()

print("DataFrame after standardizing designation text:")
display(df)

DataFrame after standardizing designation text:

,employee_id,name,designation,employment_type,salary,experience,department
0,1,Alice,software engineer,Full-time,72500.0,3.000000,Engineering
1,2,Bob,project manager,Contract,90000.0,7.000000,Management
2,3,Charlie,data scientist,Full-time,85000.0,5.000000,Data Science
3,4,David,software engineer,Full-time,72000.0,4.000000,Engineering
4,5,Eve,unknown,Part-time,60000.0,2.000000,HR
5,6,Frank,project manager,Full-time,92000.0,8.000000,Management
6,7,Grace,software engineer,Full-time,71000.0,3.000000,Engineering
7,8,Heidi,data scientist,Contract,86000.0,6.000000,Data Science
8,9,Ivan,hr manager,Full-time,62000.0,2.000000,HR
9,10,Judy,software engineer,Full-time,73000.0,4.000000,Engineering
11,11,Kelly,junior software engineer,Full-time,65000.0,4.636364,Engineering

### 4. Encode Categorical Features

I will use Label Encoding for 'designation' and 'employment_type' to convert them into numerical representations, which is suitable for many machine learning models. A new column will be created for each encoded feature.

In [ ]:
le = LabelEncoder()

df['designation_encoded'] = le.fit_transform(df['designation'])
df['employment_type_encoded'] = le.fit_transform(df['employment_type'])

print("Cleaned DataFrame with encoded categorical features:")
display(df)

print("\nFinal DataFrame Info:")
df.info()

Cleaned DataFrame with encoded categorical features:

,employee_id,name,designation,employment_type,salary,experience,department,designation_encoded,employment_type_encoded
0,1,Alice,software engineer,Full-time,72500.0,3.000000,Engineering,4,1
1,2,Bob,project manager,Contract,90000.0,7.000000,Management,3,0
2,3,Charlie,data scientist,Full-time,85000.0,5.000000,Data Science,0,1
3,4,David,software engineer,Full-time,72000.0,4.000000,Engineering,4,1
4,5,Eve,unknown,Part-time,60000.0,2.000000,HR,5,2
5,6,Frank,project manager,Full-time,92000.0,8.000000,Management,3,1
6,7,Grace,software engineer,Full-time,71000.0,3.000000,Engineering,4,1
7,8,Heidi,data scientist,Contract,86000.0,6.000000,Data Science,0,0
8,9,Ivan,hr manager,Full-time,62000.0,2.000000,HR,1,1
9,10,Judy,software engineer,Full-time,73000.0,4.000000,Engineering,4,1
11,11,Kelly,junior software engineer,Full-time,65000.0,4.636364,Engineering,2,1

Final DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   employee_id              11 non-null     int64
 1   name                     11 non-null     object
 2   designation              11 non-null     object
 3   employment_type          11 non-null     object
 4   salary                   11 non-null     float64
 5   experience               11 non-null     float64
 6   department               11 non-null     object
 7   designation_encoded      11 non-null     int64
 8   employment_type_encoded  11 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 880.0+ bytes

This cleaned dataset, `df`, is now suitable for HR analytics and prediction tasks, with missing values handled, duplicates removed, text standardized, and categorical features encoded.

In [ ]:
#TASK-2
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Create a synthetic student performance dataset
data = {
    'student_id': range(1, 21),
    'exam_date': pd.to_datetime(['2023-01-15', '2023-03-22', '2023-05-10', '2023-07-01', '2023-09-18',
                                '2023-11-05', '2023-02-28', '2023-04-12', '2023-06-30', '2023-08-01',
                                '2023-10-20', '2023-12-01', '2023-01-20', '2023-03-10', '2023-05-25',
                                '2023-07-15', '2023-09-01', '2023-11-11', '2023-02-01', '2023-04-05']),
    'course': ['Math', 'Science', 'History', 'Math', 'Science',
               'History', 'Math', 'Science', 'History', 'Math',
               'Science', 'History', 'Math', 'Science', 'History',
               'Math', 'Science', 'History', 'Math', 'Science'],
    'total_marks': [85, 72, 91, 68, 79,
                    88, 75, 62, 95, 70,
                    83, 78, 60, 92, 71,
                    80, 89, 65, 77, 90]
}
df_students = pd.DataFrame(data)

# Introduce some potential outliers in total_marks
df_students.loc[2, 'total_marks'] = 105  # High outlier
df_students.loc[18, 'total_marks'] = 20   # Low outlier

print("Original Student Performance DataFrame:")
display(df_students)
df_students.info()

Original Student Performance DataFrame:

    student_id  exam_date   course  total_marks
0            1 2023-01-15     Math           85
1            2 2023-03-22  Science           72
2            3 2023-05-10  History          105
3            4 2023-07-01     Math           68
4            5 2023-09-18  Science           79
5            6 2023-11-05  History           88
6            7 2023-02-28     Math           75
7            8 2023-04-12  Science           62
8            9 2023-06-30  History           95
9           10 2023-08-01     Math           70
10          11 2023-10-20  Science           83
11          12 2023-12-01  History           78
12          13 2023-01-20     Math           60
13          14 2023-03-10  Science           92
14          15 2023-05-25  History           71
15          16 2023-07-15     Math           80
16          17 2023-09-01  Science           89
17          18 2023-11-11  History           65
18          19 2023-02-01     Math           20
19          20 2023-04-05  Science           90

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   20 non-null     int64
 1   exam_date    20 non-null     datetime64[ns]
 2   course       20 non-null     object
 3   total_marks  20 non-null     int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 772.0+ bytes

## Student Performance Data Preprocessing Steps

### 1. Convert `exam_date` to Datetime and Extract New Features

I will ensure the `exam_date` column is in datetime format and then extract `month`, `day`, and a custom `semester` feature (assuming January-June is Semester 1 and July-December is Semester 2).

In [ ]:
# Convert 'exam_date' to datetime format (if not already)
df_students['exam_date'] = pd.to_datetime(df_students['exam_date'])

# Extract new features
df_students['exam_month'] = df_students['exam_date'].dt.month
df_students['exam_day_of_week'] = df_students['exam_date'].dt.day_name()

# Create a 'semester' feature (e.g., Jan-Jun as Semester 1, Jul-Dec as Semester 2)
df_students['semester'] = df_students['exam_date'].dt.month.apply(lambda x: 1 if x <= 6 else 2)

print("DataFrame after converting exam_date and extracting new features:")
display(df_students)

DataFrame after converting exam_date and extracting new features:

,student_id,exam_date,course,total_marks,exam_month,exam_day_of_week,semester
0,1,2023-01-15,Math,85,1,Sunday,1
1,2,2023-03-22,Science,72,3,Wednesday,1
2,3,2023-05-10,History,105,5,Wednesday,1
3,4,2023-07-01,Math,68,7,Saturday,2
4,5,2023-09-18,Science,79,9,Monday,2
5,6,2023-11-05,History,88,11,Sunday,2
6,7,2023-02-28,Math,75,2,Tuesday,1
7,8,2023-04-12,Science,62,4,Wednesday,1
8,9,2023-06-30,History,95,6,Friday,1
9,10,2023-08-01,Math,70,8,Tuesday,2
10,11,2023-10-20,Science,83,10,Friday,2
11,12,2023-12-01,History,78,12,Friday,2
12,13,2023-01-20,Math,60,1,Friday,1
13,14,2023-03-10,Science,92,3,Friday,1
14,15,2023-05-25,History,71,5,Thursday,1
15,16,2023-07-15,Math,80,7,Saturday,2
16,17,2023-09-01,Science,89,9,Friday,2
17,18,2023-11-11,History,65,11,Saturday,2
18,19,2023-02-01,Math,20,2,Wednesday,1
19,20,2023-04-05,Science,90,4,Wednesday,1

### 2. Normalize `total_marks`

I will use Min-Max scaling to normalize the `total_marks` column, transforming values to a range between 0 and 1. This is useful for algorithms sensitive to the scale of input features.

In [ ]:
# Normalize 'total_marks' using Min-Max scaling
scaler = MinMaxScaler()
df_students['total_marks_normalized'] = scaler.fit_transform(df_students[['total_marks']])

print("DataFrame after normalizing total_marks:")
display(df_students)

DataFrame after normalizing total_marks:

,student_id,exam_date,course,total_marks,exam_month,exam_day_of_week,semester,total_marks_normalized
0,1,2023-01-15,Math,85,1,Sunday,1,0.764706
1,2,2023-03-22,Science,72,3,Wednesday,1,0.611765
2,3,2023-05-10,History,105,5,Wednesday,1,1.000000
3,4,2023-07-01,Math,68,7,Saturday,2,0.564706
4,5,2023-09-18,Science,79,9,Monday,2,0.694118
5,6,2023-11-05,History,88,11,Sunday,2,0.800000
6,7,2023-02-28,Math,75,2,Tuesday,1,0.647059
7,8,2023-04-12,Science,62,4,Wednesday,1,0.494118
8,9,2023-06-30,History,95,6,Friday,1,0.882353
9,10,2023-08-01,Math,70,8,Tuesday,2,0.588235
10,11,2023-10-20,Science,83,10,Friday,2,0.741176
11,12,2023-12-01,History,78,12,Friday,2,0.682353
12,13,2023-01-20,Math,60,1,Friday,1,0.470588
13,14,2023-03-10,Science,92,3,Friday,1,0.847059
14,15,2023-05-25,History,71,5,Thursday,1,0.600000
15,16,2023-07-15,Math,80,7,Saturday,2,0.705882
16,17,2023-09-01,Science,89,9,Friday,2,0.811765
17,18,2023-11-11,History,65,11,Saturday,2,0.529412
18,19,2023-02-01,Math,20,2,Wednesday,1,0.000000
19,20,2023-04-05,Science,90,4,Wednesday,1,0.823529

### 3. Detect and Handle Outliers in `total_marks` using IQR

I will use the Interquartile Range (IQR) method to detect outliers in the `total_marks` column. Outliers will be capped to the upper and lower bounds calculated by the IQR method to mitigate their impact without removing data.

In [ ]:
# Calculate Q1, Q3, and IQR for 'total_marks'
Q1 = df_students['total_marks'].quantile(0.25)
Q3 = df_students['total_marks'].quantile(0.75)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = df_students[(df_students['total_marks'] < lower_bound) | (df_students['total_marks'] > upper_bound)]
print("Detected Outliers in total_marks:")
display(outliers)

# Handle outliers by capping them to the bounds
df_students['total_marks_cleaned'] = df_students['total_marks'].clip(lower=lower_bound, upper=upper_bound)

print("\nDataFrame after handling outliers in total_marks (capping):")
display(df_students)

print("\nFinal DataFrame Info:")
df_students.info()

Detected Outliers in total_marks:

,student_id,exam_date,course,total_marks,exam_month,exam_day_of_week,semester,total_marks_normalized
18,19,2023-02-01,Math,20,2,Wednesday,1,0.0

DataFrame after handling outliers in total_marks (capping):

,student_id,exam_date,course,total_marks,exam_month,exam_day_of_week,semester,total_marks_normalized,total_marks_cleaned
0,1,2023-01-15,Math,85,1,Sunday,1,0.764706,85.000
1,2,2023-03-22,Science,72,3,Wednesday,1,0.611765,72.000
2,3,2023-05-10,History,105,5,Wednesday,1,1.000000,105.000
3,4,2023-07-01,Math,68,7,Saturday,2,0.564706,68.000
4,5,2023-09-18,Science,79,9,Monday,2,0.694118,79.000
5,6,2023-11-05,History,88,11,Sunday,2,0.800000,88.000
6,7,2023-02-28,Math,75,2,Tuesday,1,0.647059,75.000
7,8,2023-04-12,Science,62,4,Wednesday,1,0.494118,62.000
8,9,2023-06-30,History,95,6,Friday,1,0.882353,95.000
9,10,2023-08-01,Math,70,8,Tuesday,2,0.588235,70.000
10,11,2023-10-20,Science,83,10,Friday,2,0.741176,83.000
11,12,2023-12-01,History,78,12,Friday,2,0.682353,78.000
12,13,2023-01-20,Math,60,1,Friday,1,0.470588,60.000
13,14,2023-03-10,Science,92,3,Friday,1,0.847059,92.000
14,15,2023-05-25,History,71,5,Thursday,1,0.600000,71.000
15,16,2023-07-15,Math,80,7,Saturday,2,0.705882,80.000
16,17,2023-09-01,Science,89,9,Friday,2,0.811765,89.000
17,18,2023-11-11,History,65,11,Saturday,2,0.529412,65.000
18,19,2023-02-01,Math,20,2,Wednesday,1,0.000000,41.375
19,20,2023-04-05,Science,90,4,Wednesday,1,0.823529,90.000

Final DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              20 non-null     int64
 1   exam_date               20 non-null     datetime64[ns]
 2   course                  20 non-null     object
 3   total_marks             20 non-null     int64
 4   exam_month              20 non-null     int32
 5   exam_day_of_week        20 non-null     object
 6   semester                20 non-null     int64
 7   total_marks_normalized  20 non-null     float64
 8   total_marks_cleaned     20 non-null     float64
dtypes: datetime64[ns](1), float64(2), int32(1), int64(3), object(2)
memory usage: 1.5+ KB

This transformed `df_students` dataset now includes time-based academic features (`exam_month`, `exam_day_of_week`, `semester`), normalized marks (`total_marks_normalized`), and has had outliers handled (`total_marks_cleaned`), making it suitable for further analysis.

In [ ]:
#TASK-3
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Create a synthetic student health dataset
data = {
    'student_id': range(1, 21),
    'age': [15, 16, 15, 17, 16, 15, 17, 16, 15, 17, 16, 15, 17, 16, 15, 17, 16, 15, 17, 16],
    'height_cm': [160, 175, 162, 180, 168, 165, 170, 172, 163, 178, 169, 161, 176, 171, 164, 179, 173, 166, 181, 174],
    'weight_kg': [55, 70, 58, 75, 62, 60, 68, 70, 56, 73, 65, 57, 72, 69, 59, 76, 71, 61, 78, 74],
    'medical_condition': ['None', 'Asthma', 'Allergy', 'None', 'None', 'Asthma', 'None', 'Allergy', 'None', 'None', 'Asthma', 'None', 'None', 'Allergy', 'None', 'None', 'Asthma', 'None', 'None', 'Allergy'],
    'fitness_status': ['Good', 'Excellent', 'Average', 'Excellent', 'Good', 'Average', 'Excellent', 'Good', 'Average', 'Excellent', 'Good', 'Average', 'Excellent', 'Good', 'Average', 'Excellent', 'Good', 'Average', 'Excellent', 'Good']
}
df_health = pd.DataFrame(data)

# Introduce some missing values intentionally
df_health.loc[0, 'height_cm'] = np.nan
df_health.loc[4, 'weight_kg'] = np.nan
df_health.loc[8, 'medical_condition'] = np.nan
df_health.loc[12, 'fitness_status'] = np.nan

# Calculate BMI (Body Mass Index) - weight (kg) / (height (m))^2
df_health['bmi'] = df_health['weight_kg'] / ((df_health['height_cm'] / 100)**2)

# Introduce a missing BMI intentionally
df_health.loc[1, 'bmi'] = np.nan

print("Original Student Health DataFrame:")
display(df_health)
df_health.info()

Original Student Health DataFrame:

,student_id,age,height_cm,weight_kg,medical_condition,fitness_status,bmi
0,1,15,NaN,55.0,None,Good,NaN
1,2,16,175.0,70.0,Asthma,Excellent,NaN
2,3,15,162.0,58.0,Allergy,Average,22.100290
3,4,17,180.0,75.0,None,Excellent,23.148148
4,5,16,168.0,NaN,None,Good,NaN
5,6,15,165.0,60.0,Asthma,Average,22.038567
6,7,17,170.0,68.0,None,Excellent,23.529412
7,8,16,172.0,70.0,Allergy,Good,23.661439
8,9,15,163.0,56.0,NaN,Average,21.077195
9,10,17,178.0,73.0,None,Excellent,23.040020
10,11,16,169.0,65.0,Asthma,Good,22.758307
11,12,15,161.0,57.0,None,Average,21.989892
12,13,17,176.0,72.0,None,NaN,23.243802
13,14,16,171.0,69.0,Allergy,Good,23.597004
14,15,15,164.0,59.0,None,Average,21.936347
15,16,17,179.0,76.0,None,Excellent,23.719609
16,17,16,173.0,71.0,Asthma,Good,23.722811
17,18,15,166.0,61.0,None,Average,22.136740
18,19,17,181.0,78.0,None,Excellent,23.808797
19,20,16,174.0,74.0,Allergy,Good,24.441802

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         20 non-null     int64
 1   age                20 non-null     int64
 2   height_cm          19 non-null     float64
 3   weight_kg          19 non-null     float64
 4   medical_condition  19 non-null     object
 5   fitness_status     19 non-null     object
 6   bmi                17 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 1.2+ KB

## Student Health Data Preprocessing Steps

### 1. Handle Missing Values

I will fill missing numerical values (`height_cm`, `weight_kg`, `bmi`) with their respective medians to maintain the distribution, and missing categorical values (`medical_condition`, `fitness_status`) with 'Unknown'.

In [ ]:
# Fill missing numerical values with median
df_health['height_cm'].fillna(df_health['height_cm'].median(), inplace=True)
df_health['weight_kg'].fillna(df_health['weight_kg'].median(), inplace=True)
df_health['bmi'].fillna(df_health['bmi'].median(), inplace=True)

# Fill missing categorical values with 'Unknown'
df_health['medical_condition'].fillna('Unknown', inplace=True)
df_health['fitness_status'].fillna('Unknown', inplace=True)

print("DataFrame after handling missing values:")
display(df_health)

DataFrame after handling missing values:

/tmp/ipykernel_5623/3830618996.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_health['height_cm'].fillna(df_health['height_cm'].median(), inplace=True)
/tmp/ipykernel_5623/3830618996.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_health['weight_kg'].fillna(df_health['weight_kg'].median(), inplace=True)
/tmp/ipykernel_5623/3830618996.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_health['bmi'].fillna(df_health['bmi'].median(), inplace=True)
/tmp/ipykernel_5623/3830618996.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_health['medical_condition'].fillna('Unknown', inplace=True)
/tmp/ipykernel_5623/3830618996.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_health['fitness_status'].fillna('Unknown', inplace=True)

,student_id,age,height_cm,weight_kg,medical_condition,fitness_status,bmi
0,1,15,171.0,55.0,None,Good,23.148148
1,2,16,175.0,70.0,Asthma,Excellent,23.148148
2,3,15,162.0,58.0,Allergy,Average,22.100290
3,4,17,180.0,75.0,None,Excellent,23.148148
4,5,16,168.0,69.0,None,Good,23.148148
5,6,15,165.0,60.0,Asthma,Average,22.038567
6,7,17,170.0,68.0,None,Excellent,23.529412
7,8,16,172.0,70.0,Allergy,Good,23.661439
8,9,15,163.0,56.0,Unknown,Average,21.077195
9,10,17,178.0,73.0,None,Excellent,23.040020
10,11,16,169.0,65.0,Asthma,Good,22.758307
11,12,15,161.0,57.0,None,Average,21.989892
12,13,17,176.0,72.0,None,Unknown,23.243802
13,14,16,171.0,69.0,Allergy,Good,23.597004
14,15,15,164.0,59.0,None,Average,21.936347
15,16,17,179.0,76.0,None,Excellent,23.719609
16,17,16,173.0,71.0,Asthma,Good,23.722811
17,18,15,166.0,61.0,None,Average,22.136740
18,19,17,181.0,78.0,None,Excellent,23.808797
19,20,16,174.0,74.0,Allergy,Good,24.441802

### 2. Encode Categorical Features

I will use `LabelEncoder` to convert `medical_condition` and `fitness_status` into numerical representations. New columns will be created for these encoded features.

In [ ]:
le = LabelEncoder()

df_health['medical_condition_encoded'] = le.fit_transform(df_health['medical_condition'])
df_health['fitness_status_encoded'] = le.fit_transform(df_health['fitness_status'])

print("DataFrame after encoding categorical features:")
display(df_health)

DataFrame after encoding categorical features:

,student_id,age,height_cm,weight_kg,medical_condition,fitness_status,bmi,medical_condition_encoded,fitness_status_encoded
0,1,15,171.0,55.0,None,Good,23.148148,2,2
1,2,16,175.0,70.0,Asthma,Excellent,23.148148,1,1
2,3,15,162.0,58.0,Allergy,Average,22.100290,0,0
3,4,17,180.0,75.0,None,Excellent,23.148148,2,1
4,5,16,168.0,69.0,None,Good,23.148148,2,2
5,6,15,165.0,60.0,Asthma,Average,22.038567,1,0
6,7,17,170.0,68.0,None,Excellent,23.529412,2,1
7,8,16,172.0,70.0,Allergy,Good,23.661439,0,2
8,9,15,163.0,56.0,Unknown,Average,21.077195,3,0
9,10,17,178.0,73.0,None,Excellent,23.040020,2,1
10,11,16,169.0,65.0,Asthma,Good,22.758307,1,2
11,12,15,161.0,57.0,None,Average,21.989892,2,0
12,13,17,176.0,72.0,None,Unknown,23.243802,2,3
13,14,16,171.0,69.0,Allergy,Good,23.597004,0,2
14,15,15,164.0,59.0,None,Average,21.936347,2,0
15,16,17,179.0,76.0,None,Excellent,23.719609,2,1
16,17,16,173.0,71.0,Asthma,Good,23.722811,1,2
17,18,15,166.0,61.0,None,Average,22.136740,2,0
18,19,17,181.0,78.0,None,Excellent,23.808797,2,1
19,20,16,174.0,74.0,Allergy,Good,24.441802,0,2

### 3. Scale Numerical Features

I will apply `StandardScaler` to numerical features (`age`, `height_cm`, `weight_kg`, `bmi`) to standardize them (mean=0, variance=1). This is important for many machine learning algorithms.

In [ ]:
scaler = StandardScaler()
numerical_features = ['age', 'height_cm', 'weight_kg', 'bmi']
df_health[numerical_features] = scaler.fit_transform(df_health[numerical_features])

print("DataFrame after scaling numerical features:")
display(df_health)

DataFrame after scaling numerical features:

,student_id,age,height_cm,weight_kg,medical_condition,fitness_status,bmi,medical_condition_encoded,fitness_status_encoded
0,1,-1.180603,0.016692,-1.654603,None,Good,0.218262,2,2
1,2,0.062137,0.684380,0.448706,Asthma,Excellent,0.218262,1,1
2,3,-1.180603,-1.485605,-1.233941,Allergy,Average,-1.063612,0,0
3,4,1.304877,1.518989,1.149809,None,Excellent,0.218262,2,1
4,5,0.062137,-0.484073,0.308485,None,Good,0.218262,2,2
5,6,-1.180603,-0.984839,-0.953500,Asthma,Average,-1.139118,1,0
6,7,1.304877,-0.150230,0.168265,None,Excellent,0.684672,2,1
7,8,0.062137,0.183614,0.448706,Allergy,Good,0.846184,0,2
8,9,-1.180603,-1.318683,-1.514382,Unknown,Average,-2.315191,3,0
9,10,1.304877,1.185145,0.869368,None,Excellent,0.085986,2,1
10,11,0.062137,-0.317152,-0.252397,Asthma,Good,-0.258641,1,2
11,12,-1.180603,-1.652527,-1.374162,None,Average,-1.198664,2,0
12,13,1.304877,0.851302,0.729147,None,Unknown,0.335278,2,3
13,14,0.062137,0.016692,0.308485,Allergy,Good,0.767360,0,2
14,15,-1.180603,-1.151761,-1.093721,None,Average,-1.264167,2,0
15,16,1.304877,1.352067,1.290030,None,Excellent,0.917346,2,1
16,17,0.062137,0.350536,0.588927,Asthma,Good,0.921262,1,2
17,18,-1.180603,-0.817917,-0.813279,None,Average,-1.019021,2,0
18,19,1.304877,1.685911,1.570471,None,Excellent,1.026452,2,1
19,20,0.062137,0.517458,1.009588,Allergy,Good,1.800824,0,2

### 4. Split Dataset into Training and Testing Sets

I will split the dataset into 80% training and 20% testing sets using `train_test_split`. This is a crucial step for preparing data for machine learning model development and evaluation.

In [ ]:
# Define features (X) and target (y) - for demonstration, let's assume 'fitness_status_encoded' is the target
X = df_health.drop(['student_id', 'medical_condition', 'fitness_status', 'fitness_status_encoded'], axis=1)
y = df_health['fitness_status_encoded']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

print("\nFirst 5 rows of X_train:")
display(X_train.head())
print("\nFirst 5 rows of y_train:")
display(y_train.head())

print("\nFinal DataFrame Info (after preprocessing):")
df_health.info()

Shape of X_train: (16, 5)
Shape of X_test: (4, 5)
Shape of y_train: (16,)
Shape of y_test: (4,)

First 5 rows of X_train:

         age  height_cm  weight_kg       bmi  medical_condition_encoded
8  -1.180603  -1.318683  -1.514382 -2.315191                          3
5  -1.180603  -0.984839  -0.953500 -1.139118                          1
11 -1.180603  -1.652527  -1.374162 -1.198664                          2
3   1.304877   1.518989   1.149809  0.218262                          2
18  1.304877   1.685911   1.570471  1.026452                          2

First 5 rows of y_train:

8     0
5     0
11    0
3     1
18    1
Name: fitness_status_encoded, dtype: int64

Final DataFrame Info (after preprocessing):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   student_id                 20 non-null     int64
 1   age                        20 non-null     float64
 2   height_cm                  20 non-null     float64
 3   weight_kg                  20 non-null     float64
 4   medical_condition          20 non-null     object
 5   fitness_status             20 non-null     object
 6   bmi                        20 non-null     float64
 7   medical_condition_encoded  20 non-null     int64
 8   fitness_status_encoded     20 non-null     int64
dtypes: float64(4), int64(3), object(2)
memory usage: 1.5+ KB

This preprocessed `df_health` dataset is now ready for predictive health analysis, with missing values handled, categorical features encoded, numerical features scaled, and the data split into training and testing sets.

In [ ]:
#TASK-4
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Create a synthetic ride-sharing trip dataset
data = {
    'ride_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 103, 111, 112],
    'driver_id': [1, 2, 3, 1, 4, 2, 5, 3, 4, 1, 3, 6, 5],
    'pickup_location': ['Downtown', 'Airport', 'Suburb_A', 'Downtown ', 'Suburb_B', 'Airport', 'Downtown', 'Suburb_A', 'Suburb_B ', 'Downtown', 'Suburb_A', 'Airport', 'Downtown'],
    'dropoff_location': ['Suburb_C', 'Downtown', 'City Center', 'Suburb_C ', 'Airport', 'City Center', 'Suburb_D', 'City Center ', 'Airport', 'Suburb_C', 'City Center', 'Suburb_E', 'Airport'],
    'fare_amount': [25.50, 45.00, 18.75, 26.00, np.nan, 42.50, 30.00, 19.50, 38.00, 27.00, 18.75, np.nan, 35.00],
    'distance_km': [10.2, 25.1, 7.8, 11.5, 18.0, 22.0, 13.0, 8.5, 16.5, 10.8, 7.8, 20.0, 14.5],
    'driver_rating': [4.8, 4.2, 5.0, 4.9, 3.5, 4.1, np.nan, 4.7, 3.9, 4.6, 5.0, 4.3, 4.0],
    'ride_timestamp': pd.to_datetime(['2023-10-26 08:30:00', '2023-10-26 09:15:00', '2023-10-26 10:00:00', '2023-10-26 08:45:00', '2023-10-26 11:30:00',
                                      '2023-10-26 09:30:00', '2023-10-26 12:00:00', '2023-10-26 10:30:00', '2023-10-26 11:45:00', '2023-10-26 08:50:00',
                                      '2023-10-26 10:00:00', '2023-10-26 13:00:00', '2023-10-26 12:15:00'])
}
df_rides = pd.DataFrame(data)

# Introduce some additional missing values and inconsistencies for demonstration
df_rides.loc[4, 'driver_rating'] = np.nan
df_rides.loc[6, 'fare_amount'] = np.nan
df_rides.loc[10, 'pickup_location'] = 'suburb_A'

print("Original Ride-Sharing DataFrame:")
display(df_rides)
df_rides.info()

Original Ride-Sharing DataFrame:

,ride_id,driver_id,pickup_location,dropoff_location,fare_amount,distance_km,driver_rating,ride_timestamp
0,101,1,Downtown,Suburb_C,25.50,10.2,4.8,2023-10-26 08:30:00
1,102,2,Airport,Downtown,45.00,25.1,4.2,2023-10-26 09:15:00
2,103,3,Suburb_A,City Center,18.75,7.8,5.0,2023-10-26 10:00:00
3,104,1,Downtown,Suburb_C,26.00,11.5,4.9,2023-10-26 08:45:00
4,105,4,Suburb_B,Airport,NaN,18.0,NaN,2023-10-26 11:30:00
5,106,2,Airport,City Center,42.50,22.0,4.1,2023-10-26 09:30:00
6,107,5,Downtown,Suburb_D,NaN,13.0,NaN,2023-10-26 12:00:00
7,108,3,Suburb_A,City Center,19.50,8.5,4.7,2023-10-26 10:30:00
8,109,4,Suburb_B,Airport,38.00,16.5,3.9,2023-10-26 11:45:00
9,110,1,Downtown,Suburb_C,27.00,10.8,4.6,2023-10-26 08:50:00
10,103,3,suburb_A,City Center,18.75,7.8,5.0,2023-10-26 10:00:00
11,111,6,Airport,Suburb_E,NaN,20.0,4.3,2023-10-26 13:00:00
12,112,5,Downtown,Airport,35.00,14.5,4.0,2023-10-26 12:15:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ride_id           13 non-null     int64
 1   driver_id         13 non-null     int64
 2   pickup_location   13 non-null     object
 3   dropoff_location  13 non-null     object
 4   fare_amount       10 non-null     float64
 5   distance_km       13 non-null     float64
 6   driver_rating     11 non-null     float64
 7   ride_timestamp    13 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(2), object(2)
memory usage: 964.0+ bytes

## Ride-Sharing Data Cleaning Steps

### 1. Standardize Pickup and Dropoff Locations

I will remove leading/trailing whitespace and convert text to title case for `pickup_location` and `dropoff_location` to ensure consistency.

In [ ]:
df_rides['pickup_location'] = df_rides['pickup_location'].str.strip().str.title()
df_rides['dropoff_location'] = df_rides['dropoff_location'].str.strip().str.title()

print("DataFrame after standardizing locations:")
display(df_rides)

DataFrame after standardizing locations:

,ride_id,driver_id,pickup_location,dropoff_location,fare_amount,distance_km,driver_rating,ride_timestamp
0,101,1,Downtown,Suburb_C,25.50,10.2,4.8,2023-10-26 08:30:00
1,102,2,Airport,Downtown,45.00,25.1,4.2,2023-10-26 09:15:00
2,103,3,Suburb_A,City Center,18.75,7.8,5.0,2023-10-26 10:00:00
3,104,1,Downtown,Suburb_C,26.00,11.5,4.9,2023-10-26 08:45:00
4,105,4,Suburb_B,Airport,NaN,18.0,NaN,2023-10-26 11:30:00
5,106,2,Airport,City Center,42.50,22.0,4.1,2023-10-26 09:30:00
6,107,5,Downtown,Suburb_D,NaN,13.0,NaN,2023-10-26 12:00:00
7,108,3,Suburb_A,City Center,19.50,8.5,4.7,2023-10-26 10:30:00
8,109,4,Suburb_B,Airport,38.00,16.5,3.9,2023-10-26 11:45:00
9,110,1,Downtown,Suburb_C,27.00,10.8,4.6,2023-10-26 08:50:00
10,103,3,Suburb_A,City Center,18.75,7.8,5.0,2023-10-26 10:00:00
11,111,6,Airport,Suburb_E,NaN,20.0,4.3,2023-10-26 13:00:00
12,112,5,Downtown,Airport,35.00,14.5,4.0,2023-10-26 12:15:00

### 2. Fill Missing Fare Amounts with Median Values

Missing `fare_amount` values will be filled with the median of the column to maintain the distribution's central tendency without being heavily influenced by outliers.

In [ ]:
df_rides['fare_amount'].fillna(df_rides['fare_amount'].median(), inplace=True)

print("DataFrame after filling missing fare amounts:")
display(df_rides)

DataFrame after filling missing fare amounts:

/tmp/ipykernel_5623/1510598533.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rides['fare_amount'].fillna(df_rides['fare_amount'].median(), inplace=True)

,ride_id,driver_id,pickup_location,dropoff_location,fare_amount,distance_km,driver_rating,ride_timestamp
0,101,1,Downtown,Suburb_C,25.50,10.2,4.8,2023-10-26 08:30:00
1,102,2,Airport,Downtown,45.00,25.1,4.2,2023-10-26 09:15:00
2,103,3,Suburb_A,City Center,18.75,7.8,5.0,2023-10-26 10:00:00
3,104,1,Downtown,Suburb_C,26.00,11.5,4.9,2023-10-26 08:45:00
4,105,4,Suburb_B,Airport,26.50,18.0,NaN,2023-10-26 11:30:00
5,106,2,Airport,City Center,42.50,22.0,4.1,2023-10-26 09:30:00
6,107,5,Downtown,Suburb_D,26.50,13.0,NaN,2023-10-26 12:00:00
7,108,3,Suburb_A,City Center,19.50,8.5,4.7,2023-10-26 10:30:00
8,109,4,Suburb_B,Airport,38.00,16.5,3.9,2023-10-26 11:45:00
9,110,1,Downtown,Suburb_C,27.00,10.8,4.6,2023-10-26 08:50:00
10,103,3,Suburb_A,City Center,18.75,7.8,5.0,2023-10-26 10:00:00
11,111,6,Airport,Suburb_E,26.50,20.0,4.3,2023-10-26 13:00:00
12,112,5,Downtown,Airport,35.00,14.5,4.0,2023-10-26 12:15:00

### 3. Remove Duplicate Ride Entries

I will remove duplicate rows based on `ride_id` to ensure each ride is unique, keeping the first occurrence if duplicates exist.

In [ ]:
df_rides.drop_duplicates(subset=['ride_id'], keep='first', inplace=True)

print("DataFrame after removing duplicate ride entries:")
display(df_rides)

DataFrame after removing duplicate ride entries:

,ride_id,driver_id,pickup_location,dropoff_location,fare_amount,distance_km,driver_rating,ride_timestamp
0,101,1,Downtown,Suburb_C,25.50,10.2,4.8,2023-10-26 08:30:00
1,102,2,Airport,Downtown,45.00,25.1,4.2,2023-10-26 09:15:00
2,103,3,Suburb_A,City Center,18.75,7.8,5.0,2023-10-26 10:00:00
3,104,1,Downtown,Suburb_C,26.00,11.5,4.9,2023-10-26 08:45:00
4,105,4,Suburb_B,Airport,26.50,18.0,NaN,2023-10-26 11:30:00
5,106,2,Airport,City Center,42.50,22.0,4.1,2023-10-26 09:30:00
6,107,5,Downtown,Suburb_D,26.50,13.0,NaN,2023-10-26 12:00:00
7,108,3,Suburb_A,City Center,19.50,8.5,4.7,2023-10-26 10:30:00
8,109,4,Suburb_B,Airport,38.00,16.5,3.9,2023-10-26 11:45:00
9,110,1,Downtown,Suburb_C,27.00,10.8,4.6,2023-10-26 08:50:00
11,111,6,Airport,Suburb_E,26.50,20.0,4.3,2023-10-26 13:00:00
12,112,5,Downtown,Airport,35.00,14.5,4.0,2023-10-26 12:15:00

### 4. Normalize Driver Ratings

I will use Min-Max scaling to normalize `driver_rating` to a range between 0 and 1, which is useful for algorithms sensitive to feature scales. Missing ratings will first be filled with the mean.

In [ ]:
# Fill missing driver ratings with the mean before normalization
df_rides['driver_rating'].fillna(df_rides['driver_rating'].mean(), inplace=True)

# Normalize 'driver_rating' using Min-Max scaling
scaler = MinMaxScaler()
df_rides['driver_rating_normalized'] = scaler.fit_transform(df_rides[['driver_rating']])

print("DataFrame after normalizing driver ratings:")
display(df_rides)

DataFrame after normalizing driver ratings:

/tmp/ipykernel_5623/3088369718.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rides['driver_rating'].fillna(df_rides['driver_rating'].mean(), inplace=True)

,ride_id,driver_id,pickup_location,dropoff_location,fare_amount,distance_km,driver_rating,ride_timestamp,driver_rating_normalized
0,101,1,Downtown,Suburb_C,25.50,10.2,4.80,2023-10-26 08:30:00,0.818182
1,102,2,Airport,Downtown,45.00,25.1,4.20,2023-10-26 09:15:00,0.272727
2,103,3,Suburb_A,City Center,18.75,7.8,5.00,2023-10-26 10:00:00,1.000000
3,104,1,Downtown,Suburb_C,26.00,11.5,4.90,2023-10-26 08:45:00,0.909091
4,105,4,Suburb_B,Airport,26.50,18.0,4.45,2023-10-26 11:30:00,0.500000
5,106,2,Airport,City Center,42.50,22.0,4.10,2023-10-26 09:30:00,0.181818
6,107,5,Downtown,Suburb_D,26.50,13.0,4.45,2023-10-26 12:00:00,0.500000
7,108,3,Suburb_A,City Center,19.50,8.5,4.70,2023-10-26 10:30:00,0.727273
8,109,4,Suburb_B,Airport,38.00,16.5,3.90,2023-10-26 11:45:00,0.000000
9,110,1,Downtown,Suburb_C,27.00,10.8,4.60,2023-10-26 08:50:00,0.636364
11,111,6,Airport,Suburb_E,26.50,20.0,4.30,2023-10-26 13:00:00,0.363636
12,112,5,Downtown,Airport,35.00,14.5,4.00,2023-10-26 12:15:00,0.090909

### 5. Generate a Summary of Data Improvements

Here is a summary of the cleaning steps performed and the resulting state of the dataset.

In [ ]:
print("\n--- Summary of Data Improvements ---")
print(f"Original number of rows: {len(data['ride_id'])}")
print(f"Rows after removing duplicates: {len(df_rides)}")
print("\nMissing values after cleaning:")
print(df_rides.isnull().sum())
print("\nDataFrame Info after cleaning:")
df_rides.info()

print("\nSample of the cleaned DataFrame:")
display(df_rides.head())

--- Summary of Data Improvements ---
Original number of rows: 13
Rows after removing duplicates: 12

Missing values after cleaning:
ride_id                     0
driver_id                   0
pickup_location             0
dropoff_location            0
fare_amount                 0
distance_km                 0
driver_rating               0
ride_timestamp              0
driver_rating_normalized    0
dtype: int64

DataFrame Info after cleaning:
<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 12
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ride_id                   12 non-null     int64
 1   driver_id                 12 non-null     int64
 2   pickup_location           12 non-null     object
 3   dropoff_location          12 non-null     object
 4   fare_amount               12 non-null     float64
 5   distance_km               12 non-null     float64
 6   driver_rating             12 non-null     float64
 7   ride_timestamp            12 non-null     datetime64[ns]
 8   driver_rating_normalized  12 non-null     float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(2)
memory usage: 960.0+ bytes

Sample of the cleaned DataFrame:

,ride_id,driver_id,pickup_location,dropoff_location,fare_amount,distance_km,driver_rating,ride_timestamp,driver_rating_normalized
0,101,1,Downtown,Suburb_C,25.50,10.2,4.80,2023-10-26 08:30:00,0.818182
1,102,2,Airport,Downtown,45.00,25.1,4.20,2023-10-26 09:15:00,0.272727
2,103,3,Suburb_A,City Center,18.75,7.8,5.00,2023-10-26 10:00:00,1.000000
3,104,1,Downtown,Suburb_C,26.00,11.5,4.90,2023-10-26 08:45:00,0.909091
4,105,4,Suburb_B,Airport,26.50,18.0,4.45,2023-10-26 11:30:00,0.500000

This cleaned ride-sharing dataset, `df_rides`, is now ready for operational analysis, with standardized locations, handled missing fare amounts and driver ratings, removed duplicate entries, and normalized driver ratings.